### ISSUE TITLE
PHP代码 颜色问题

### ISSUE THREAD

**Issue by syunaht** [wnanbei/typora-theme-flora#1]
先感谢大大的主题，很漂亮！个人很喜欢

今天突然发现php代码似乎对于颜色没有调整，默认蓝色实在看不清代码，怎么调背景都不行

后来网上搜了搜，干脆抄了下 ursine-polar的配置，没学过相关内容，应该没有啥大问题吧
.cm-s-inner span.cm-variable-2 {
  color: #01a0e4;
}

希望能多多优化这个主题！
感谢！

**Comment by wnanbei** [comment]
你修改了代码的话，可以提交一下 Pull Requests 哦，我可以合到主题里

**Comment by wnanbei** [comment]
@KagamigawaMeguri

**Comment by syunaht** [comment]
感谢回复
已提交！

**Comment by wnanbei** [comment]
新的修改已经发布了新版本，这个 issue 我就关闭了 @KagamigawaMeguri
