### ISSUE TITLE
标题标签选择问题

### ISSUE THREAD

**Issue by joechenrh** [wnanbei/typora-theme-flora#3]
![1](https://user-images.githubusercontent.com/18008525/89485398-47268700-d7d3-11ea-9b2d-a85857647a3b.gif)
在使用此主题时，不能通过鼠标单击来选择标题的编辑位置，请问作者知道如何解决吗？谢谢

**Comment by joechenrh** [comment]
经过穷举法，发现问题出在 `#write h3::before` 的 `right` 和 `bottom` 属性，去掉就好了

不过显示效果就会有点变化

![image](https://user-images.githubusercontent.com/18008525/89487736-d4200f00-d7d8-11ea-8c39-e93717a5456b.png)

**Comment by wnanbei** [comment]
这个应该是 h3~h6 标题的样式导致展示的位置和实际的位置不太一样，实际的位置比展示的位置偏右，你试一下长一点的标题可以看出来。
我研究下怎么解决这个问题。

**Comment by HeXueZhi** [comment]
![QQ截图20201009215142](https://user-images.githubusercontent.com/52291143/95591996-9d859f80-0a7a-11eb-8be6-0067c3a17bcc.png)
改这里就行
