### ISSUE TITLE
可以出一个深夜模式的版本吗

### ISSUE THREAD

**Issue by chen-zhuohan** [wnanbei/typora-theme-flora#4]
非常非常喜欢作者的主题，中英混合显示效果非常好，找了半天也没找到显示效果更好的主题。只是看习惯了深夜模式编辑器的我，看这个有点晃眼睛，可以出一个深夜模式的版本吗？感谢！

**Comment by HeXueZhi** [comment]
> 非常非常喜欢作者的主题，中英混合显示效果非常好，找了半天也没找到显示效果更好的主题。只是看习惯了深夜模式编辑器的我，看这个有点晃眼睛，可以出一个深夜模式的版本吗？感谢！

正在学习前端，基于作者大神的CSS代码改了一份暗色主题：[https://github.com/HeXueZhi/typora-theme-FloraDark](https://github.com/HeXueZhi/typora-theme-FloraDark)，如果有帮助到您，请帮忙点个star。（当然先给原作者点star:blush:）

**Comment by chen-zhuohan** [comment]
非常感谢，效果非常好！

**Comment by wnanbei** [comment]
> > 非常非常喜欢作者的主题，中英混合显示效果非常好，找了半天也没找到显示效果更好的主题。只是看习惯了深夜模式编辑器的我，看这个有点晃眼睛，可以出一个深夜模式的版本吗？感谢！
> 
> 正在学习前端，基于作者大神的CSS代码改了一份暗色主题：https://github.com/HeXueZhi/typora-theme-FloraDark，如果有帮助到您，请帮忙点个star。（当然先给原作者点star😊）

有兴趣提交一个PR吗，暗色的很棒

**Comment by wnanbei** [comment]
@HeXueZhi

**Comment by HeXueZhi** [comment]
> @HeXueZhi

谢谢大佬的夸奖:blush:，PR已经提交。（话说上午去实验室没带笔记本，抱歉现在才回复）

**Comment by HeXueZhi** [comment]
另外想给大佬一个建议，可以将这个主题更新到Typora官网的主题git仓库，让更多的人看到这个主题。

**Comment by HeXueZhi** [comment]
> 非常非常喜欢作者的主题，中英混合显示效果非常好，找了半天也没找到显示效果更好的主题。只是看习惯了深夜模式编辑器的我，看这个有点晃眼睛，可以出一个深夜模式的版本吗？感谢！

我发行了暗色主题1.0.1版本，主要修复了**标题选择**和**mark样式**的问题。麻烦重新下载主题。[https://github.com/HeXueZhi/typora-theme-FloraDark/releases](https://github.com/HeXueZhi/typora-theme-FloraDark/releases)

**Comment by wnanbei** [comment]
> 另外想给大佬一个建议，可以将这个主题更新到Typora官网的主题git仓库，让更多的人看到这个主题。

其实在官网上有，不过这个主题最开始是起自于 ursine，所以这个主题放在 ursine 主题页里面的下方，不太起眼。
我过几天去试试申请单独放到一个页面。
感谢贡献啦~
